import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const moduleFrom=async(path,suffix)=>import('data:text/javascript;base64,'+Buffer.from(readFileSync(path,'utf8')+'\n//'+suffix).toString('base64'));
const store=new Map();let clock=Date.now();const realNow=Date.now;Date.now=()=>clock;
globalThis.caches={default:{async match(key){const item=store.get(key.url);return item&&item.expires>clock?new Response(item.body,{headers:{'Content-Type':'application/json'}}):undefined},async put(key,response){const seconds=Number(response.headers.get('Cache-Control').match(/max-age=(\d+)/)[1]);store.set(key.url,{body:await response.text(),expires:clock+seconds*1000})}}};
const html=`<script>const cond_barra=[{"condicao_barra":"1"}];</script><p>Manobras previstas</p><p>09/10/2026 | 10:30 ETB | Entrada | BERCO1 | BE | NAVIO TESTE | ROTA | 200 | 30 | 10 | Previsto</p><p>Navios Atracados</p><p>Manobras Realizadas</p><p>08/10/2026 | NAVIO ANTERIOR | Saída | BERCO1 | 200 | 30 | 09:00 ATS | 10 | ROTA | BE | 2</p>`;
let calls=0,fail=false,slow=false;globalThis.fetch=async(url,options)=>{calls++;assert(options.signal);if(slow)return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))));if(fail)return new Response('offline',{status:503});await new Promise(r=>setTimeout(r,10));return new Response(html)};
const ships=await moduleFrom('functions/api/movimentacao-navios.js','ships');const context={request:new Request('https://panel.example/api/movimentacao-navios?atualizar=1')};let response=await ships.onRequestGet(context),data=await response.json();assert.equal(data.sucesso,true);assert.equal(data.desatualizado,false);assert.equal(data.proximasManobras[0].navio,'NAVIO TESTE');assert.equal(data.condicaoBarra.status,'PRATICÁVEL');assert.equal(calls,1);context.request=new Request('https://panel.example/api/movimentacao-navios?atualizar=999');data=await(await ships.onRequestGet(context)).json();assert.equal(data.cache,true);assert.equal(calls,1);
clock+=61000;const simultaneous=await Promise.all(Array.from({length:8},()=>ships.onRequestGet(context)));assert.equal(calls,2);for(const r of simultaneous)assert.equal((await r.json()).sucesso,true);
clock+=61000;fail=true;data=await(await ships.onRequestGet(context)).json();assert.equal(data.desatualizado,true);const savedAt=data.atualizadoEm;assert(data.aviso);clock+=16000;data=await(await ships.onRequestGet(context)).json();assert.equal(data.atualizadoEm,savedAt);
store.clear();response=await ships.onRequestGet(context);assert.equal(response.status,503);assert.equal((await response.json()).sucesso,false);
// Timers shortened only for the timeout test; source must still receive an aborted signal.
const originalTimer=setTimeout;globalThis.setTimeout=(fn,ms,...args)=>originalTimer(fn,ms===8000?5:ms,...args);fail=false;slow=true;response=await ships.onRequestGet(context);assert.equal(response.status,503);globalThis.setTimeout=originalTimer;Date.now=realNow;
let payloads=[];globalThis.fetch=async(url,options)=>{payloads.push(JSON.parse(options.body));assert.equal(options.headers['x-goog-api-key'],'test-key');return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'Texto revisado'}]}}]}),{headers:{'Content-Type':'application/json'}})};
const gemini=await moduleFrom('functions/api/gemini.js','gemini'),env={GEMINI_API_KEY:'test-key'};
function request(body,headers={},raw=false){return new Request('https://panel.example/api/gemini',{method:'POST',headers:{Origin:'https://panel.example','Content-Type':'application/json','CF-Connecting-IP':'198.51.100.1',...headers},body:raw?body:JSON.stringify(body)})}
for(const acao of ['corrigir','melhorar','formal','simplificar','resumir','traduzir']){const r=await gemini.onRequestPost({env,request:request({acao,text:'Teste'})});assert.equal(r.status,200);assert.equal((await r.json()).result,'Texto revisado')}
assert.equal((await gemini.onRequestPost({env,request:request({action:'corrigir',text:'Teste'})})).status,200);
assert.equal((await gemini.onRequestPost({env,request:request({acao:'unknown',text:'Teste'})})).status,400);assert.equal((await gemini.onRequestPost({env,request:request('{',{},true)})).status,400);assert.equal((await gemini.onRequestPost({env,request:request(null)})).status,400);assert.equal((await gemini.onRequestPost({env,request:request({acao:'corrigir',text:'x'.repeat(20001)})})).status,413);assert.equal((await gemini.onRequestPost({env,request:request({acao:'corrigir',text:'Teste'},{Origin:'https://other.example'})})).status,403);assert.equal((await gemini.onRequestPost({env:{},request:request({acao:'corrigir',text:'Teste'})})).status,503);assert.equal((await gemini.onRequestPost({env,request:request('x'.repeat(120001),{},true)})).status,413);
for(let i=0;i<3;i++)assert.equal((await gemini.onRequestPost({env,request:request({acao:'corrigir',text:'Teste'})})).status,200);const limited=await gemini.onRequestPost({env,request:request({acao:'corrigir',text:'Teste'})});assert.equal(limited.status,429);assert.equal(limited.headers.get('Retry-After'),'60');assert.equal(payloads.length,10);
assert.equal((await gemini.onRequestPost({env:{...env,AI_RATE_LIMITER:{limit:async()=>({success:false})}},request:request({acao:'corrigir',text:'Teste'})})).status,429);
console.log('PASS APIs: parsing realista, cache compartilhado/consulta normalizada, requisições simultâneas, cópia antiga, falta de cópia, timeout, 6 ações do Editor, contrato antigo, origem/JSON/tamanho/chave e limitação de requisições.');
